import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { StatusColorProvider } from "@/components/providers/StatusColorProvider";
import { prisma } from "@/lib/db/prisma";

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  let initialThemes: Record<string, string> = {}
  try {
    const statusColors = await prisma.statusColor.findMany()
    statusColors.forEach(sc => {
      initialThemes[sc.status] = sc.theme
    })
  } catch (e) {
    console.error("Failed to fetch status colors", e)
  }

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <StatusColorProvider initialThemes={initialThemes}>
          {children}
        </StatusColorProvider>
      </body>
    </html>
  );
}
